#!/usr/bin/env python2.7

import sys
from tuby import main

if __name__ == '__main__':
	debug = False
	argv = []
	argv.extend(sys.argv)
	stdin = sys.stdin
	name = 'tb-help'
	numarg = len(argv)
	if numarg > 1:
		name = sys.argv[1]
	if numarg > 2:
		if sys.argv[2] != '-':
			stdin = open(sys.argv[2], 'rb')
	try:
		main(name, stdin=stdin, debug=debug)
	except KeyboardInterrupt:
		print 'Got Ctrl-C, interrupting.'
	except Exception as e:
		print 'Error: %s' % e
	sys.exit(0)
